Add lifts to `Output[Option[List[A]]]` etc.
VirtusLab/besom pull request #445
Opened 2024-04-09 06:37 UTC by pawelprazak

Fixes #424

2024-04-09 09:16 UTC, pawelprazak commented
Added the requested `getOrFail`, and scaladocs for public methods.

2024-04-09 11:28 UTC, lbialy requested changes

2024-04-09 11:28 UTC, lbialy commented on core/src/main/scala/besom/internal/Output.scala
> +    /** Calls [[List.tail]] on the underlying [[List]], but does not throw on `Nil`
fail instead of throw

2024-04-09 11:28 UTC, lbialy commented on core/src/main/scala/besom/internal/Output.scala
> +    /** Calls [[List.init]] on the underlying [[List]], but does not throw on `Nil`
fail instead of throw

2024-04-09 13:08 UTC, pawelprazak commented
Addressed the comments. Extended signatures of mapInner / flatMap inner for lists to match option. Added unit tests.

2024-04-10 11:10 UTC, lbialy approved these changes

2024-04-10 11:10 UTC, merged